//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnxProject_Franco.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourtCaseDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourtCaseDetails()
        {
            this.QAs = new HashSet<QAs>();
        }
    
        public int CaseId { get; set; }
        public int ID { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public int StatusId { get; set; }
    
        public virtual CourtCases CourtCases { get; set; }
        public virtual States States { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QAs> QAs { get; set; }
    }
}
