//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnxProject_Franco.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourtCaseDetails
    {
        public int IDCourtCaseDetail { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public int IDStatus { get; set; }
        public int IDCourtCase { get; set; }
    }
}
