//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnxProject_Franco.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lawyers
    {
        public int IDLawyer { get; set; }
        public int ProfessionalLicense { get; set; }
        public System.DateTime ContractDate { get; set; }
        public int IDCourtBranch { get; set; }
        public int IDPerson { get; set; }
    }
}
