//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnxProject_Franco.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int CourtBranchId { get; set; }
        public string Body { get; set; }
        public string Place { get; set; }
        public System.DateTime Date { get; set; }
        public string LetterHead { get; set; }
        public int ScopeID { get; set; }
    
        public virtual CourtBranches CourtBranches { get; set; }
        public virtual Scopes Scopes { get; set; }
    }
}
