//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnxProject_Franco.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QAs()
        {
            this.Lawyers = new HashSet<Lawyers>();
        }
    
        public int ID { get; set; }
        public int CourtCaseDetailID { get; set; }
        public string Query { get; set; }
        public System.DateTime SendDate { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> AnswerDate { get; set; }
    
        public virtual CourtCaseDetails CourtCaseDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lawyers> Lawyers { get; set; }
    }
}
